//
//  UIColor+Fripple.swift
//
//  Generated by Zeplin on 8/18/15.
//  Copyright (c) 2015 __Fripple__. All rights reserved.
//

import UIKit

extension UIColor {
    
    class func isYellowColor() -> UIColor {
        return UIColor(red: 253.0 / 255.0, green: 183.0 / 255.0, blue: 53.0 / 255.0, alpha: 1.0)
    }

    class func isGreenColor() -> UIColor {
        return UIColor(red: 120.0 / 255.0, green: 245.0 / 255.0, blue: 135.0 / 255.0, alpha: 1.0)
    }

    class func isRedColor() -> UIColor {
        return UIColor(red: 220.0 / 255.0, green: 28.0 / 255.0, blue: 135.0 / 255.0, alpha: 1.0)
    }
    
    class func isBrownColor() -> UIColor {
        return UIColor(red: 222.0 / 255.0, green: 188.0 / 255.0, blue: 153.0 / 255.0, alpha: 1.0)
    }

}
